require 'codelog/version'
require 'codelog/cli'
require 'codelog/command/setup'
require 'codelog/command/new'
require 'codelog/command/release'
require 'codelog/command/step/changelog'
require 'codelog/command/step/delete'
require 'codelog/command/step/version'
